name: Cleanup Workflow Records
run-name: Cleanup Workflow Records

on:
  workflow_run:
    workflows: ["Convert Rules to MRS for Adblock"]
    types:
      - completed
  workflow_dispatch:

permissions:
  actions: write 
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete all workflow runs except the latest
        run: |
          REPO="${{ github.repository }}"
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"

          WORKFLOWS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO/actions/runs")
          echo "$WORKFLOWS"

          RUN_IDS=$(echo "$WORKFLOWS" | jq -r '.workflow_runs | if . == null then [] else .[] | .id end')

          FIRST=true
          for RUN_ID in $RUN_IDS; do
            if [ "$FIRST" = true ]; then
              FIRST=false
              continue
            fi
            echo "Deleting workflow run $RUN_ID"
            curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID"
          done

          echo "All workflow runs except the latest have been deleted."
